plugins:
  rustfmt:
    path: ../tree-sitter-lint-plugin-rustfmt
  rust-known-imports:
    path: ../tree-sitter-lint-plugin-rust-known-imports
rules:
  rustfmt/rustfmt:
    level: error
  rust-known-imports/known-imports:
    level: error
    options:
      known_imports:
        ClassStaticBlock:
          module: crate::kind
          kind: static
        Comment:
          module: crate::kind
          kind: static
        ContinueStatement:
          module: crate::kind
          kind: static
        EmptyStatement:
          module: crate::kind
          kind: static
        ForInStatement:
          module: crate::kind
          kind: static
        Identifier:
          module: crate::kind
          kind: static
        IfStatement:
          module: crate::kind
          kind: static
        MemberExpression:
          module: crate::kind
          kind: static
        Object:
          module: crate::kind
          kind: static
        StatementBlock:
          module: crate::kind
          kind: static
        SubscriptExpression:
          module: crate::kind
          kind: static
        upper_case_first:
          module: crate::string_utils
          kind: function
        ast_utils:
          module: crate::utils
          kind: module
        get_instance_provider_factory:
          module: crate
          kind: function
        ScopeManager:
          module: crate::scope
          kind: type
        ScopeType:
          module: crate::scope
          kind: type
        get_comment_type:
          module: crate::ast_helpers
          kind: function
        get_comment_contents:
          module: crate::ast_helpers
          kind: function
        CommentType:
          module: crate::ast_helpers
          kind: type
        skip_parentheses:
          module: crate::ast_helpers
          kind: trait_method
          trait: NodeExtJs
        QueryMatchContext:
          module: tree_sitter_lint
          kind: type
        Rule:
          module: tree_sitter_lint
          kind: type
        RuleTestExpectedErrorBuilder:
          module: tree_sitter_lint
          kind: type
        SkipOptionsBuilder:
          module: tree_sitter_lint
          kind: type
        rule:
          module: tree_sitter_lint
          kind: macro
        violation:
          module: tree_sitter_lint
          kind: macro
        has_child_of_kind:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        first_non_comment_named_child:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        non_comment_named_children:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        text:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        tokens:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        num_non_comment_named_children:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        field:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        TreeCursor:
          module: tree_sitter_lint::tree_sitter
          kind: type
        Node:
          module: tree_sitter_lint::tree_sitter
          kind: type
        Tree:
          module: tree_sitter_lint::tree_sitter
          kind: type
        SupportedLanguage:
          module: tree_sitter_lint::tree_sitter_grep
          kind: type
        Deserialize:
          module: serde
          kind: type
        return_default_if_none:
          module: squalid
          kind: macro
        return_if_none:
          module: squalid
          kind: macro
        run_once:
          module: squalid
          kind: macro
        json_object:
          module: squalid
          kind: macro
        regex:
          module: squalid
          kind: macro
        matches:
          module: squalid
          kind: trait_method
          trait: OptionExt
        then_and:
          module: squalid
          kind: trait_method
          trait: BoolExt
        thrush:
          module: squalid
          kind: trait_method
          trait: EverythingExt
        as_double_deref:
          module: squalid
          kind: trait_method
          trait: OptionExtDeref
        sorted:
          module: squalid
          kind: trait_method
          trait: SliceExtCloneOrd
        non_empty:
          module: squalid
          kind: trait_method
          trait: NonEmpty
        Regex:
          module: regex
          kind: type
        Either:
          module: itertools
          kind: type
        collect_vec:
          module: itertools
          kind: trait_method
          trait: Itertools
        instrument:
          module: tracing
          kind: attribute
        trace:
          module: tracing
          kind: macro
        Ref:
          module: std::cell
          kind: type
        HashSet:
          module: std::collections
          kind: type
        HashMap:
          module: std::collections
          kind: type
        Arc:
          module: std::sync
          kind: type
tree-sitter-lint-dependency:
  path: ../tree-sitter-lint
