plugins:
  rustfmt:
    path: ../tree-sitter-lint-plugin-rustfmt
  rust-known-imports:
    path: ../tree-sitter-lint-plugin-rust-known-imports
rules:
  rustfmt/rustfmt:
    level: error
  rust-known-imports/no-undef:
    level: error
    options:
      known_imports:
        QueryMatchContext:
          module: tree_sitter_lint
          kind: type_identifier
        TreeCursor:
          module: tree_sitter
          kind: type_identifier
        Node:
          module: tree_sitter
          kind: type_identifier
        SupportedLanguage:
          module: tree_sitter_lint::tree_sitter_grep
          kind: type_identifier
        has_child_of_kind:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        Deserialize:
          module: serde
          kind: type_identifier
        HashMap:
          module: std::collections
          kind: type_identifier
        matches:
          module: squalid
          kind: trait_method
          trait: OptionExt
        return_default_if_none:
          module: squalid
          kind: macro
        then_and:
          module: squalid
          kind: trait_method
          trait: BoolExt
tree-sitter-lint-dependency:
  path: ../tree-sitter-lint
