plugins:
  rustfmt:
    path: ../tree-sitter-lint-plugin-rustfmt
  rust-known-imports:
    path: ../tree-sitter-lint-plugin-rust-known-imports
rules:
  rustfmt/rustfmt:
    level: error
  rust-known-imports/known-imports:
    level: error
    options:
      known_imports:
        get_instance_provider_factory:
          module: crate
          kind: function
        AllComments:
          module: crate::all_comments
          kind: type
        CommentType:
          module: crate::ast_helpers
          kind: type
        get_call_expression_arguments:
          module: crate::ast_helpers
          kind: function
        get_comment_type:
          module: crate::ast_helpers
          kind: function
        get_comment_contents:
          module: crate::ast_helpers
          kind: function
        get_method_definition_kind:
          module: crate::ast_helpers
          kind: function
        is_class_member_static:
          module: crate::ast_helpers
          kind: function
        is_jsx_tag_name:
          module: crate::ast_helpers
          kind: function
        MethodDefinitionKind:
          module: crate::ast_helpers
          kind: type
        next_non_parentheses_ancestor:
          module: crate::ast_helpers
          kind: trait_method
          trait: NodeExtJs
        skip_parentheses:
          module: crate::ast_helpers
          kind: trait_method
          trait: NodeExtJs
        globals:
          module: crate::conf
          kind: module
        DirectiveComments:
          module: crate::directive_comments
          kind: type
        directives_pattern:
          module: crate::directives
          kind: static
        Arguments:
          module: crate::kind
          kind: static
        ArrowFunction:
          module: crate::kind
          kind: static
        CallExpression:
          module: crate::kind
          kind: static
        ClassStaticBlock:
          module: crate::kind
          kind: static
        Comment:
          module: crate::kind
          kind: static
        ComputedPropertyName:
          module: crate::kind
          kind: static
        ContinueStatement:
          module: crate::kind
          kind: static
        EmptyStatement:
          module: crate::kind
          kind: static
        ExportStatement:
          module: crate::kind
          kind: static
        ForInStatement:
          module: crate::kind
          kind: static
        Function:
          module: crate::kind
          kind: static
        FunctionDeclaration:
          module: crate::kind
          kind: static
        GeneratorFunction:
          module: crate::kind
          kind: static
        GeneratorFunctionDeclaration:
          module: crate::kind
          kind: static
        Identifier:
          module: crate::kind
          kind: static
        IfStatement:
          module: crate::kind
          kind: static
        JsxOpeningElement:
          module: crate::kind
          kind: static
        JsxSelfClosingElement:
          module: crate::kind
          kind: static
        MemberExpression:
          module: crate::kind
          kind: static
        MethodDefinition:
          module: crate::kind
          kind: static
        Object:
          module: crate::kind
          kind: static
        Pair:
          module: crate::kind
          kind: static
        Program:
          module: crate::kind
          kind: static
        PropertyIdentifier:
          module: crate::kind
          kind: static
        StatementBlock:
          module: crate::kind
          kind: static
        SubscriptExpression:
          module: crate::kind
          kind: static
        UnaryExpression:
          module: crate::kind
          kind: static
        VariableDeclaration:
          module: crate::kind
          kind: static
        Kind:
          module: crate::kind
          kind: type
        config_comment_parser:
          module: crate::scope
          kind: type
        ScopeManager:
          module: crate::scope
          kind: type
        ScopeType:
          module: crate::scope
          kind: type
        upper_case_first:
          module: crate::string_utils
          kind: function
        ast_utils:
          module: crate::utils
          kind: module
        FileRunContext:
          module: tree_sitter_lint
          kind: type
        FromFileRunContext:
          module: tree_sitter_lint
          kind: type
        QueryMatchContext:
          module: tree_sitter_lint
          kind: type
        Rule:
          module: tree_sitter_lint
          kind: type
        RuleTestExpectedErrorBuilder:
          module: tree_sitter_lint
          kind: type
        SkipOptionsBuilder:
          module: tree_sitter_lint
          kind: type
        rule:
          module: tree_sitter_lint
          kind: macro
        violation:
          module: tree_sitter_lint
          kind: macro
        has_child_of_kind:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        first_non_comment_named_child:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        non_comment_named_children:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        text:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        tokens:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        num_non_comment_named_children:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        field:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        tid:
          module: tree_sitter_lint::better_any
          kind: macro
        TreeCursor:
          module: tree_sitter_lint::tree_sitter
          kind: type
        Node:
          module: tree_sitter_lint::tree_sitter
          kind: type
        Tree:
          module: tree_sitter_lint::tree_sitter
          kind: type
        RopeOrSlice:
          module: tree_sitter_lint::tree_sitter_grep
          kind: type
        SupportedLanguage:
          module: tree_sitter_lint::tree_sitter_grep
          kind: type
        Deserialize:
          module: serde
          kind: type
        return_default_if_none:
          module: squalid
          kind: macro
        return_if_none:
          module: squalid
          kind: macro
        run_once:
          module: squalid
          kind: macro
        json_object:
          module: squalid
          kind: macro
        regex:
          module: squalid
          kind: macro
        matches:
          module: squalid
          kind: trait_method
          trait: OptionExt
        then_and:
          module: squalid
          kind: trait_method
          trait: BoolExt
        thrush:
          module: squalid
          kind: trait_method
          trait: EverythingExt
        when:
          module: squalid
          kind: trait_method
          trait: EverythingExt
        as_double_deref:
          module: squalid
          kind: trait_method
          trait: OptionExtDeref
        sorted:
          module: squalid
          kind: trait_method
          trait: SliceExtCloneOrd
        non_empty:
          module: squalid
          kind: trait_method
          trait: NonEmpty
        Captures:
          module: regex
          kind: type
        Regex:
          module: regex
          kind: type
        Either:
          module: itertools
          kind: type
        collect_vec:
          module: itertools
          kind: trait_method
          trait: Itertools
        instrument:
          module: tracing
          kind: attribute
        trace:
          module: tracing
          kind: macro
        Lazy:
          module: once_cell::sync
          kind: type
        iter:
          module: std
          kind: module
        Ref:
          module: std::cell
          kind: type
        HashSet:
          module: std::collections
          kind: type
        HashMap:
          module: std::collections
          kind: type
        Arc:
          module: std::sync
          kind: type
        Cow:
          module: std::borrow
          kind: type
tree-sitter-lint-dependency:
  path: ../tree-sitter-lint
