plugins:
  rustfmt:
    path: ../tree-sitter-lint-plugin-rustfmt
  rust-known-imports:
    path: ../tree-sitter-lint-plugin-rust-known-imports
rules:
  rustfmt/rustfmt:
    level: error
  rust-known-imports/known-imports:
    level: error
    options:
      known_imports:
        QueryMatchContext:
          module: tree_sitter_lint
          kind: type_identifier
        TreeCursor:
          module: tree_sitter
          kind: type_identifier
        Node:
          module: tree_sitter
          kind: type_identifier
        SupportedLanguage:
          module: tree_sitter_lint::tree_sitter_grep
          kind: type_identifier
        has_child_of_kind:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        Deserialize:
          module: serde
          kind: type_identifier
        HashMap:
          module: std::collections
          kind: type_identifier
        matches:
          module: squalid
          kind: trait_method
          trait: OptionExt
        return_default_if_none:
          module: squalid
          kind: macro
        then_and:
          module: squalid
          kind: trait_method
          trait: BoolExt
        collect_vec:
          module: itertools
          kind: trait_method
          trait: Itertools
        thrush:
          module: squalid
          kind: trait_method
          trait: EverythingExt
        return_if_none:
          module: squalid
          kind: macro
        as_double_deref:
          module: squalid
          kind: trait_method
          trait: OptionExtDeref
        non_empty:
          module: squalid
          kind: trait_method
          trait: NonEmpty
        Either:
          module: itertools
          kind: type_identifier
        first_non_comment_named_child:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        non_comment_named_children:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        Tree:
          module: tree_sitter_lint::tree_sitter
          kind: type_identifier
        Ref:
          module: std::cell
          kind: type_identifier
        instrument:
          module: tracing
          kind: attribute
        trace:
          module: tracing
          kind: macro
        run_once:
          module: squalid
          kind: macro
        text:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
        sorted:
          module: squalid
          kind: trait_method
          trait: SliceExtCloneOrd
        HashSet:
          module: std::collections
          kind: type_identifier
        tokens:
          module: tree_sitter_lint
          kind: trait_method
          trait: NodeExt
tree-sitter-lint-dependency:
  path: ../tree-sitter-lint
