[package]
name = "tree-sitter-lint-plugin-eslint-builtin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
Inflector = "0.11.4"
const_format = "0.2.31"
id-arena = "2.2.1"
once_cell = "1.18.0"
regex = "1.9.1"
serde = "1.0.178"
squalid = { git = "https://github.com/helixbass/squalid", rev = "7ea7971" }
tree-sitter-lint = { path = "../tree-sitter-lint" }
itertools = "0.11.0"
fancy-regex = "0.11.0"

[patch.crates-io]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "c16b90d" }
