[package]
name = "tree-sitter-lint-plugin-eslint-builtin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.31"
once_cell = "1.18.0"
regex = "1.9.1"
serde = "1.0.178"
# squalid = { git = "https://github.com/helixbass/squalid", rev = "bc7108a" }
squalid = { path = "../squalid" }
tree-sitter-lint = { path = "../tree-sitter-lint" }

[patch.crates-io]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "c16b90d" }
