[workspace]
members = [
    "plugin",
    "xtask"
]

[workspace.dependencies]
tree-sitter-lint = { path = "../tree-sitter-lint" }

[patch.crates-io]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "c16b90d" }
