[workspace]
members = [
    "plugin",
    "xtask"
]
resolver = "2"

[workspace.dependencies]
tree-sitter-lint = { git = "https://github.com/helixbass/tree-sitter-lint", rev = "05bb8e8" }

[patch.crates-io]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "660481d" }
