use std::{borrow::Cow, collections::HashMap, fmt};

use once_cell::sync::Lazy;
use serde::{
    de::{self, Unexpected},
    Deserialize, Deserializer,
};
use squalid::HashMapExt;

pub type Globals = HashMap<Cow<'static, str>, Visibility>;

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Visibility {
    Readonly,
    Writable,
    #[allow(dead_code)]
    Off,
}

impl<'de> Deserialize<'de> for Visibility {
    fn deserialize<TDeserializer>(deserializer: TDeserializer) -> Result<Self, TDeserializer::Error>
    where
        TDeserializer: Deserializer<'de>,
    {
        deserializer.deserialize_any(VisibilityDeserializeVisitor)
    }
}

struct VisibilityDeserializeVisitor;

impl<'de> de::Visitor<'de> for VisibilityDeserializeVisitor {
    type Value = Visibility;

    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        formatter.write_str("true/false/\"readonly\"/\"writable\"/\"readable\"/\"writeable\"")
    }

    fn visit_bool<TError>(self, value: bool) -> Result<Self::Value, TError>
    where
        TError: de::Error,
    {
        Ok(match value {
            true => Visibility::Writable,
            false => Visibility::Readonly,
        })
    }

    fn visit_str<TError>(self, value: &str) -> Result<Self::Value, TError>
    where
        TError: de::Error,
    {
        match value {
            "readonly" | "readable" | "false" => Ok(Visibility::Readonly),
            "writable" | "writeable" | "true" => Ok(Visibility::Writable),
            "off" => Ok(Visibility::Off),
            value => Err(de::Error::invalid_value(Unexpected::Str(value), &self)),
        }
    }

    fn visit_unit<TError>(self) -> Result<Self::Value, TError>
    where
        TError: de::Error,
    {
        Ok(Visibility::Readonly)
    }
}

pub static COMMONJS: Lazy<Globals> = Lazy::new(|| {
    [
        (Cow::Borrowed("exports"), Visibility::Writable),
        (Cow::Borrowed("global"), Visibility::Readonly),
        (Cow::Borrowed("module"), Visibility::Readonly),
        (Cow::Borrowed("require"), Visibility::Readonly),
    ]
    .into()
});

pub static ES3: Lazy<Globals> = Lazy::new(|| {
    [
        (Cow::Borrowed("Array"), Visibility::Readonly),
        (Cow::Borrowed("Boolean"), Visibility::Readonly),
        (Cow::Borrowed("constructor"), Visibility::Readonly),
        (Cow::Borrowed("Date"), Visibility::Readonly),
        (Cow::Borrowed("decodeURI"), Visibility::Readonly),
        (Cow::Borrowed("decodeURIComponent"), Visibility::Readonly),
        (Cow::Borrowed("encodeURI"), Visibility::Readonly),
        (Cow::Borrowed("encodeURIComponent"), Visibility::Readonly),
        (Cow::Borrowed("Error"), Visibility::Readonly),
        (Cow::Borrowed("escape"), Visibility::Readonly),
        (Cow::Borrowed("eval"), Visibility::Readonly),
        (Cow::Borrowed("EvalError"), Visibility::Readonly),
        (Cow::Borrowed("Function"), Visibility::Readonly),
        (Cow::Borrowed("hasOwnProperty"), Visibility::Readonly),
        (Cow::Borrowed("Infinity"), Visibility::Readonly),
        (Cow::Borrowed("isFinite"), Visibility::Readonly),
        (Cow::Borrowed("isNaN"), Visibility::Readonly),
        (Cow::Borrowed("isPrototypeOf"), Visibility::Readonly),
        (Cow::Borrowed("Math"), Visibility::Readonly),
        (Cow::Borrowed("NaN"), Visibility::Readonly),
        (Cow::Borrowed("Number"), Visibility::Readonly),
        (Cow::Borrowed("Object"), Visibility::Readonly),
        (Cow::Borrowed("parseFloat"), Visibility::Readonly),
        (Cow::Borrowed("parseInt"), Visibility::Readonly),
        (Cow::Borrowed("propertyIsEnumerable"), Visibility::Readonly),
        (Cow::Borrowed("RangeError"), Visibility::Readonly),
        (Cow::Borrowed("ReferenceError"), Visibility::Readonly),
        (Cow::Borrowed("RegExp"), Visibility::Readonly),
        (Cow::Borrowed("String"), Visibility::Readonly),
        (Cow::Borrowed("SyntaxError"), Visibility::Readonly),
        (Cow::Borrowed("toLocaleString"), Visibility::Readonly),
        (Cow::Borrowed("toString"), Visibility::Readonly),
        (Cow::Borrowed("TypeError"), Visibility::Readonly),
        (Cow::Borrowed("undefined"), Visibility::Readonly),
        (Cow::Borrowed("unescape"), Visibility::Readonly),
        (Cow::Borrowed("URIError"), Visibility::Readonly),
        (Cow::Borrowed("valueOf"), Visibility::Readonly),
    ]
    .into()
});

pub static ES5: Lazy<Globals> = Lazy::new(|| {
    ES3.clone()
        .and_extend([(Cow::Borrowed("JSON"), Visibility::Readonly)])
});

pub static ES2015: Lazy<Globals> = Lazy::new(|| {
    ES5.clone().and_extend([
        (Cow::Borrowed("ArrayBuffer"), Visibility::Readonly),
        (Cow::Borrowed("DataView"), Visibility::Readonly),
        (Cow::Borrowed("Float32Array"), Visibility::Readonly),
        (Cow::Borrowed("Float64Array"), Visibility::Readonly),
        (Cow::Borrowed("Int16Array"), Visibility::Readonly),
        (Cow::Borrowed("Int32Array"), Visibility::Readonly),
        (Cow::Borrowed("Int8Array"), Visibility::Readonly),
        (Cow::Borrowed("Map"), Visibility::Readonly),
        (Cow::Borrowed("Promise"), Visibility::Readonly),
        (Cow::Borrowed("Proxy"), Visibility::Readonly),
        (Cow::Borrowed("Reflect"), Visibility::Readonly),
        (Cow::Borrowed("Set"), Visibility::Readonly),
        (Cow::Borrowed("Symbol"), Visibility::Readonly),
        (Cow::Borrowed("Uint16Array"), Visibility::Readonly),
        (Cow::Borrowed("Uint32Array"), Visibility::Readonly),
        (Cow::Borrowed("Uint8Array"), Visibility::Readonly),
        (Cow::Borrowed("Uint8ClampedArray"), Visibility::Readonly),
        (Cow::Borrowed("WeakMap"), Visibility::Readonly),
        (Cow::Borrowed("WeakSet"), Visibility::Readonly),
    ])
});

pub static ES2016: Lazy<Globals> = Lazy::new(|| ES2015.clone());

pub static ES2017: Lazy<Globals> = Lazy::new(|| {
    ES2016.clone().and_extend([
        (Cow::Borrowed("Atomics"), Visibility::Readonly),
        (Cow::Borrowed("SharedArrayBuffer"), Visibility::Readonly),
    ])
});

pub static ES2018: Lazy<Globals> = Lazy::new(|| ES2017.clone());

pub static ES2019: Lazy<Globals> = Lazy::new(|| ES2018.clone());

pub static ES2020: Lazy<Globals> = Lazy::new(|| {
    ES2019.clone().and_extend([
        (Cow::Borrowed("BigInt"), Visibility::Readonly),
        (Cow::Borrowed("BigInt64Array"), Visibility::Readonly),
        (Cow::Borrowed("BigUint64Array"), Visibility::Readonly),
        (Cow::Borrowed("globalThis"), Visibility::Readonly),
    ])
});

pub static ES2021: Lazy<Globals> = Lazy::new(|| {
    ES2020.clone().and_extend([
        (Cow::Borrowed("AggregateError"), Visibility::Readonly),
        (Cow::Borrowed("FinalizationRegistry"), Visibility::Readonly),
        (Cow::Borrowed("WeakRef"), Visibility::Readonly),
    ])
});

pub static ES2022: Lazy<Globals> = Lazy::new(|| ES2021.clone());

pub static ES2023: Lazy<Globals> = Lazy::new(|| ES2022.clone());

pub static ES2024: Lazy<Globals> = Lazy::new(|| ES2023.clone());

pub static BUILTIN: Lazy<Globals> = Lazy::new(|| ES2023.clone());

pub static BROWSER: Lazy<Globals> = Lazy::new(|| {
    [
        (Cow::Borrowed("AbortController"), Visibility::Readonly),
        (Cow::Borrowed("AbortSignal"), Visibility::Readonly),
        (Cow::Borrowed("addEventListener"), Visibility::Readonly),
        (Cow::Borrowed("alert"), Visibility::Readonly),
        (Cow::Borrowed("AnalyserNode"), Visibility::Readonly),
        (Cow::Borrowed("Animation"), Visibility::Readonly),
        (
            Cow::Borrowed("AnimationEffectReadOnly"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("AnimationEffectTiming"), Visibility::Readonly),
        (
            Cow::Borrowed("AnimationEffectTimingReadOnly"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("AnimationEvent"), Visibility::Readonly),
        (
            Cow::Borrowed("AnimationPlaybackEvent"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("AnimationTimeline"), Visibility::Readonly),
        (Cow::Borrowed("applicationCache"), Visibility::Readonly),
        (Cow::Borrowed("ApplicationCache"), Visibility::Readonly),
        (
            Cow::Borrowed("ApplicationCacheErrorEvent"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("atob"), Visibility::Readonly),
        (Cow::Borrowed("Attr"), Visibility::Readonly),
        (Cow::Borrowed("Audio"), Visibility::Readonly),
        (Cow::Borrowed("AudioBuffer"), Visibility::Readonly),
        (Cow::Borrowed("AudioBufferSourceNode"), Visibility::Readonly),
        (Cow::Borrowed("AudioContext"), Visibility::Readonly),
        (Cow::Borrowed("AudioDestinationNode"), Visibility::Readonly),
        (Cow::Borrowed("AudioListener"), Visibility::Readonly),
        (Cow::Borrowed("AudioNode"), Visibility::Readonly),
        (Cow::Borrowed("AudioParam"), Visibility::Readonly),
        (Cow::Borrowed("AudioProcessingEvent"), Visibility::Readonly),
        (
            Cow::Borrowed("AudioScheduledSourceNode"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("AudioWorkletGlobalScope"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("AudioWorkletNode"), Visibility::Readonly),
        (Cow::Borrowed("AudioWorkletProcessor"), Visibility::Readonly),
        (Cow::Borrowed("BarProp"), Visibility::Readonly),
        (Cow::Borrowed("BaseAudioContext"), Visibility::Readonly),
        (Cow::Borrowed("BatteryManager"), Visibility::Readonly),
        (Cow::Borrowed("BeforeUnloadEvent"), Visibility::Readonly),
        (Cow::Borrowed("BiquadFilterNode"), Visibility::Readonly),
        (Cow::Borrowed("Blob"), Visibility::Readonly),
        (Cow::Borrowed("BlobEvent"), Visibility::Readonly),
        (Cow::Borrowed("blur"), Visibility::Readonly),
        (Cow::Borrowed("BroadcastChannel"), Visibility::Readonly),
        (Cow::Borrowed("btoa"), Visibility::Readonly),
        (Cow::Borrowed("BudgetService"), Visibility::Readonly),
        (
            Cow::Borrowed("ByteLengthQueuingStrategy"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("Cache"), Visibility::Readonly),
        (Cow::Borrowed("caches"), Visibility::Readonly),
        (Cow::Borrowed("CacheStorage"), Visibility::Readonly),
        (Cow::Borrowed("cancelAnimationFrame"), Visibility::Readonly),
        (Cow::Borrowed("cancelIdleCallback"), Visibility::Readonly),
        (
            Cow::Borrowed("CanvasCaptureMediaStreamTrack"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("CanvasGradient"), Visibility::Readonly),
        (Cow::Borrowed("CanvasPattern"), Visibility::Readonly),
        (
            Cow::Borrowed("CanvasRenderingContext2D"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("ChannelMergerNode"), Visibility::Readonly),
        (Cow::Borrowed("ChannelSplitterNode"), Visibility::Readonly),
        (Cow::Borrowed("CharacterData"), Visibility::Readonly),
        (Cow::Borrowed("clearInterval"), Visibility::Readonly),
        (Cow::Borrowed("clearTimeout"), Visibility::Readonly),
        (Cow::Borrowed("clientInformation"), Visibility::Readonly),
        (Cow::Borrowed("ClipboardEvent"), Visibility::Readonly),
        (Cow::Borrowed("ClipboardItem"), Visibility::Readonly),
        (Cow::Borrowed("close"), Visibility::Readonly),
        (Cow::Borrowed("closed"), Visibility::Readonly),
        (Cow::Borrowed("CloseEvent"), Visibility::Readonly),
        (Cow::Borrowed("Comment"), Visibility::Readonly),
        (Cow::Borrowed("CompositionEvent"), Visibility::Readonly),
        (Cow::Borrowed("CompressionStream"), Visibility::Readonly),
        (Cow::Borrowed("confirm"), Visibility::Readonly),
        (Cow::Borrowed("console"), Visibility::Readonly),
        (Cow::Borrowed("ConstantSourceNode"), Visibility::Readonly),
        (Cow::Borrowed("ConvolverNode"), Visibility::Readonly),
        (Cow::Borrowed("CountQueuingStrategy"), Visibility::Readonly),
        (Cow::Borrowed("createImageBitmap"), Visibility::Readonly),
        (Cow::Borrowed("Credential"), Visibility::Readonly),
        (Cow::Borrowed("CredentialsContainer"), Visibility::Readonly),
        (Cow::Borrowed("crypto"), Visibility::Readonly),
        (Cow::Borrowed("Crypto"), Visibility::Readonly),
        (Cow::Borrowed("CryptoKey"), Visibility::Readonly),
        (Cow::Borrowed("CSS"), Visibility::Readonly),
        (Cow::Borrowed("CSSConditionRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSFontFaceRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSGroupingRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSImportRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSKeyframeRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSKeyframesRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSMatrixComponent"), Visibility::Readonly),
        (Cow::Borrowed("CSSMediaRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSNamespaceRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSPageRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSPerspective"), Visibility::Readonly),
        (Cow::Borrowed("CSSRotate"), Visibility::Readonly),
        (Cow::Borrowed("CSSRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSRuleList"), Visibility::Readonly),
        (Cow::Borrowed("CSSScale"), Visibility::Readonly),
        (Cow::Borrowed("CSSSkew"), Visibility::Readonly),
        (Cow::Borrowed("CSSSkewX"), Visibility::Readonly),
        (Cow::Borrowed("CSSSkewY"), Visibility::Readonly),
        (Cow::Borrowed("CSSStyleDeclaration"), Visibility::Readonly),
        (Cow::Borrowed("CSSStyleRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSStyleSheet"), Visibility::Readonly),
        (Cow::Borrowed("CSSSupportsRule"), Visibility::Readonly),
        (Cow::Borrowed("CSSTransformValue"), Visibility::Readonly),
        (Cow::Borrowed("CSSTranslate"), Visibility::Readonly),
        (Cow::Borrowed("CustomElementRegistry"), Visibility::Readonly),
        (Cow::Borrowed("customElements"), Visibility::Readonly),
        (Cow::Borrowed("CustomEvent"), Visibility::Readonly),
        (Cow::Borrowed("DataTransfer"), Visibility::Readonly),
        (Cow::Borrowed("DataTransferItem"), Visibility::Readonly),
        (Cow::Borrowed("DataTransferItemList"), Visibility::Readonly),
        (Cow::Borrowed("DecompressionStream"), Visibility::Readonly),
        (Cow::Borrowed("defaultstatus"), Visibility::Readonly),
        (Cow::Borrowed("defaultStatus"), Visibility::Readonly),
        (Cow::Borrowed("DelayNode"), Visibility::Readonly),
        (Cow::Borrowed("DeviceMotionEvent"), Visibility::Readonly),
        (
            Cow::Borrowed("DeviceOrientationEvent"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("devicePixelRatio"), Visibility::Readonly),
        (Cow::Borrowed("dispatchEvent"), Visibility::Readonly),
        (Cow::Borrowed("document"), Visibility::Readonly),
        (Cow::Borrowed("Document"), Visibility::Readonly),
        (Cow::Borrowed("DocumentFragment"), Visibility::Readonly),
        (Cow::Borrowed("DocumentType"), Visibility::Readonly),
        (Cow::Borrowed("DOMError"), Visibility::Readonly),
        (Cow::Borrowed("DOMException"), Visibility::Readonly),
        (Cow::Borrowed("DOMImplementation"), Visibility::Readonly),
        (Cow::Borrowed("DOMMatrix"), Visibility::Readonly),
        (Cow::Borrowed("DOMMatrixReadOnly"), Visibility::Readonly),
        (Cow::Borrowed("DOMParser"), Visibility::Readonly),
        (Cow::Borrowed("DOMPoint"), Visibility::Readonly),
        (Cow::Borrowed("DOMPointReadOnly"), Visibility::Readonly),
        (Cow::Borrowed("DOMQuad"), Visibility::Readonly),
        (Cow::Borrowed("DOMRect"), Visibility::Readonly),
        (Cow::Borrowed("DOMRectList"), Visibility::Readonly),
        (Cow::Borrowed("DOMRectReadOnly"), Visibility::Readonly),
        (Cow::Borrowed("DOMStringList"), Visibility::Readonly),
        (Cow::Borrowed("DOMStringMap"), Visibility::Readonly),
        (Cow::Borrowed("DOMTokenList"), Visibility::Readonly),
        (Cow::Borrowed("DragEvent"), Visibility::Readonly),
        (
            Cow::Borrowed("DynamicsCompressorNode"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("Element"), Visibility::Readonly),
        (Cow::Borrowed("ErrorEvent"), Visibility::Readonly),
        (Cow::Borrowed("event"), Visibility::Readonly),
        (Cow::Borrowed("Event"), Visibility::Readonly),
        (Cow::Borrowed("EventSource"), Visibility::Readonly),
        (Cow::Borrowed("EventTarget"), Visibility::Readonly),
        (Cow::Borrowed("external"), Visibility::Readonly),
        (Cow::Borrowed("fetch"), Visibility::Readonly),
        (Cow::Borrowed("File"), Visibility::Readonly),
        (Cow::Borrowed("FileList"), Visibility::Readonly),
        (Cow::Borrowed("FileReader"), Visibility::Readonly),
        (Cow::Borrowed("find"), Visibility::Readonly),
        (Cow::Borrowed("focus"), Visibility::Readonly),
        (Cow::Borrowed("FocusEvent"), Visibility::Readonly),
        (Cow::Borrowed("FontFace"), Visibility::Readonly),
        (Cow::Borrowed("FontFaceSetLoadEvent"), Visibility::Readonly),
        (Cow::Borrowed("FormData"), Visibility::Readonly),
        (Cow::Borrowed("FormDataEvent"), Visibility::Readonly),
        (Cow::Borrowed("frameElement"), Visibility::Readonly),
        (Cow::Borrowed("frames"), Visibility::Readonly),
        (Cow::Borrowed("GainNode"), Visibility::Readonly),
        (Cow::Borrowed("Gamepad"), Visibility::Readonly),
        (Cow::Borrowed("GamepadButton"), Visibility::Readonly),
        (Cow::Borrowed("GamepadEvent"), Visibility::Readonly),
        (Cow::Borrowed("getComputedStyle"), Visibility::Readonly),
        (Cow::Borrowed("getSelection"), Visibility::Readonly),
        (Cow::Borrowed("HashChangeEvent"), Visibility::Readonly),
        (Cow::Borrowed("Headers"), Visibility::Readonly),
        (Cow::Borrowed("history"), Visibility::Readonly),
        (Cow::Borrowed("History"), Visibility::Readonly),
        (Cow::Borrowed("HTMLAllCollection"), Visibility::Readonly),
        (Cow::Borrowed("HTMLAnchorElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLAreaElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLAudioElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLBaseElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLBodyElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLBRElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLButtonElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLCanvasElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLCollection"), Visibility::Readonly),
        (Cow::Borrowed("HTMLContentElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDataElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDataListElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDetailsElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDialogElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDirectoryElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDivElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDListElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLDocument"), Visibility::Readonly),
        (Cow::Borrowed("HTMLElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLEmbedElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLFieldSetElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLFontElement"), Visibility::Readonly),
        (
            Cow::Borrowed("HTMLFormControlsCollection"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("HTMLFormElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLFrameElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLFrameSetElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLHeadElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLHeadingElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLHRElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLHtmlElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLIFrameElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLImageElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLInputElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLLabelElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLLegendElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLLIElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLLinkElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLMapElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLMarqueeElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLMediaElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLMenuElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLMetaElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLMeterElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLModElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLObjectElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLOListElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLOptGroupElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLOptionElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLOptionsCollection"), Visibility::Readonly),
        (Cow::Borrowed("HTMLOutputElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLParagraphElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLParamElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLPictureElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLPreElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLProgressElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLQuoteElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLScriptElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLSelectElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLShadowElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLSlotElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLSourceElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLSpanElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLStyleElement"), Visibility::Readonly),
        (
            Cow::Borrowed("HTMLTableCaptionElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("HTMLTableCellElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTableColElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTableElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTableRowElement"), Visibility::Readonly),
        (
            Cow::Borrowed("HTMLTableSectionElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("HTMLTemplateElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTextAreaElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTimeElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTitleElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLTrackElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLUListElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLUnknownElement"), Visibility::Readonly),
        (Cow::Borrowed("HTMLVideoElement"), Visibility::Readonly),
        (Cow::Borrowed("IDBCursor"), Visibility::Readonly),
        (Cow::Borrowed("IDBCursorWithValue"), Visibility::Readonly),
        (Cow::Borrowed("IDBDatabase"), Visibility::Readonly),
        (Cow::Borrowed("IDBFactory"), Visibility::Readonly),
        (Cow::Borrowed("IDBIndex"), Visibility::Readonly),
        (Cow::Borrowed("IDBKeyRange"), Visibility::Readonly),
        (Cow::Borrowed("IDBObjectStore"), Visibility::Readonly),
        (Cow::Borrowed("IDBOpenDBRequest"), Visibility::Readonly),
        (Cow::Borrowed("IDBRequest"), Visibility::Readonly),
        (Cow::Borrowed("IDBTransaction"), Visibility::Readonly),
        (Cow::Borrowed("IDBVersionChangeEvent"), Visibility::Readonly),
        (Cow::Borrowed("IdleDeadline"), Visibility::Readonly),
        (Cow::Borrowed("IIRFilterNode"), Visibility::Readonly),
        (Cow::Borrowed("Image"), Visibility::Readonly),
        (Cow::Borrowed("ImageBitmap"), Visibility::Readonly),
        (
            Cow::Borrowed("ImageBitmapRenderingContext"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("ImageCapture"), Visibility::Readonly),
        (Cow::Borrowed("ImageData"), Visibility::Readonly),
        (Cow::Borrowed("indexedDB"), Visibility::Readonly),
        (Cow::Borrowed("innerHeight"), Visibility::Readonly),
        (Cow::Borrowed("innerWidth"), Visibility::Readonly),
        (Cow::Borrowed("InputEvent"), Visibility::Readonly),
        (Cow::Borrowed("IntersectionObserver"), Visibility::Readonly),
        (
            Cow::Borrowed("IntersectionObserverEntry"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("Intl"), Visibility::Readonly),
        (Cow::Borrowed("isSecureContext"), Visibility::Readonly),
        (Cow::Borrowed("KeyboardEvent"), Visibility::Readonly),
        (Cow::Borrowed("KeyframeEffect"), Visibility::Readonly),
        (
            Cow::Borrowed("KeyframeEffectReadOnly"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("length"), Visibility::Readonly),
        (Cow::Borrowed("localStorage"), Visibility::Readonly),
        (Cow::Borrowed("location"), Visibility::Writable),
        (Cow::Borrowed("Location"), Visibility::Readonly),
        (Cow::Borrowed("locationbar"), Visibility::Readonly),
        (Cow::Borrowed("matchMedia"), Visibility::Readonly),
        (Cow::Borrowed("MediaDeviceInfo"), Visibility::Readonly),
        (Cow::Borrowed("MediaDevices"), Visibility::Readonly),
        (
            Cow::Borrowed("MediaElementAudioSourceNode"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("MediaEncryptedEvent"), Visibility::Readonly),
        (Cow::Borrowed("MediaError"), Visibility::Readonly),
        (Cow::Borrowed("MediaKeyMessageEvent"), Visibility::Readonly),
        (Cow::Borrowed("MediaKeySession"), Visibility::Readonly),
        (Cow::Borrowed("MediaKeyStatusMap"), Visibility::Readonly),
        (Cow::Borrowed("MediaKeySystemAccess"), Visibility::Readonly),
        (Cow::Borrowed("MediaList"), Visibility::Readonly),
        (Cow::Borrowed("MediaMetadata"), Visibility::Readonly),
        (Cow::Borrowed("MediaQueryList"), Visibility::Readonly),
        (Cow::Borrowed("MediaQueryListEvent"), Visibility::Readonly),
        (Cow::Borrowed("MediaRecorder"), Visibility::Readonly),
        (Cow::Borrowed("MediaSettingsRange"), Visibility::Readonly),
        (Cow::Borrowed("MediaSource"), Visibility::Readonly),
        (Cow::Borrowed("MediaStream"), Visibility::Readonly),
        (
            Cow::Borrowed("MediaStreamAudioDestinationNode"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("MediaStreamAudioSourceNode"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("MediaStreamConstraints"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("MediaStreamEvent"), Visibility::Readonly),
        (Cow::Borrowed("MediaStreamTrack"), Visibility::Readonly),
        (Cow::Borrowed("MediaStreamTrackEvent"), Visibility::Readonly),
        (Cow::Borrowed("menubar"), Visibility::Readonly),
        (Cow::Borrowed("MessageChannel"), Visibility::Readonly),
        (Cow::Borrowed("MessageEvent"), Visibility::Readonly),
        (Cow::Borrowed("MessagePort"), Visibility::Readonly),
        (Cow::Borrowed("MIDIAccess"), Visibility::Readonly),
        (Cow::Borrowed("MIDIConnectionEvent"), Visibility::Readonly),
        (Cow::Borrowed("MIDIInput"), Visibility::Readonly),
        (Cow::Borrowed("MIDIInputMap"), Visibility::Readonly),
        (Cow::Borrowed("MIDIMessageEvent"), Visibility::Readonly),
        (Cow::Borrowed("MIDIOutput"), Visibility::Readonly),
        (Cow::Borrowed("MIDIOutputMap"), Visibility::Readonly),
        (Cow::Borrowed("MIDIPort"), Visibility::Readonly),
        (Cow::Borrowed("MimeType"), Visibility::Readonly),
        (Cow::Borrowed("MimeTypeArray"), Visibility::Readonly),
        (Cow::Borrowed("MouseEvent"), Visibility::Readonly),
        (Cow::Borrowed("moveBy"), Visibility::Readonly),
        (Cow::Borrowed("moveTo"), Visibility::Readonly),
        (Cow::Borrowed("MutationEvent"), Visibility::Readonly),
        (Cow::Borrowed("MutationObserver"), Visibility::Readonly),
        (Cow::Borrowed("MutationRecord"), Visibility::Readonly),
        (Cow::Borrowed("name"), Visibility::Readonly),
        (Cow::Borrowed("NamedNodeMap"), Visibility::Readonly),
        (
            Cow::Borrowed("NavigationPreloadManager"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("navigator"), Visibility::Readonly),
        (Cow::Borrowed("Navigator"), Visibility::Readonly),
        (Cow::Borrowed("NavigatorUAData"), Visibility::Readonly),
        (Cow::Borrowed("NetworkInformation"), Visibility::Readonly),
        (Cow::Borrowed("Node"), Visibility::Readonly),
        (Cow::Borrowed("NodeFilter"), Visibility::Readonly),
        (Cow::Borrowed("NodeIterator"), Visibility::Readonly),
        (Cow::Borrowed("NodeList"), Visibility::Readonly),
        (Cow::Borrowed("Notification"), Visibility::Readonly),
        (
            Cow::Borrowed("OfflineAudioCompletionEvent"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("OfflineAudioContext"), Visibility::Readonly),
        (Cow::Borrowed("offscreenBuffering"), Visibility::Readonly),
        (Cow::Borrowed("OffscreenCanvas"), Visibility::Writable),
        (
            Cow::Borrowed("OffscreenCanvasRenderingContext2D"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("onabort"), Visibility::Writable),
        (Cow::Borrowed("onafterprint"), Visibility::Writable),
        (Cow::Borrowed("onanimationend"), Visibility::Writable),
        (Cow::Borrowed("onanimationiteration"), Visibility::Writable),
        (Cow::Borrowed("onanimationstart"), Visibility::Writable),
        (Cow::Borrowed("onappinstalled"), Visibility::Writable),
        (Cow::Borrowed("onauxclick"), Visibility::Writable),
        (Cow::Borrowed("onbeforeinstallprompt"), Visibility::Writable),
        (Cow::Borrowed("onbeforeprint"), Visibility::Writable),
        (Cow::Borrowed("onbeforeunload"), Visibility::Writable),
        (Cow::Borrowed("onblur"), Visibility::Writable),
        (Cow::Borrowed("oncancel"), Visibility::Writable),
        (Cow::Borrowed("oncanplay"), Visibility::Writable),
        (Cow::Borrowed("oncanplaythrough"), Visibility::Writable),
        (Cow::Borrowed("onchange"), Visibility::Writable),
        (Cow::Borrowed("onclick"), Visibility::Writable),
        (Cow::Borrowed("onclose"), Visibility::Writable),
        (Cow::Borrowed("oncontextmenu"), Visibility::Writable),
        (Cow::Borrowed("oncuechange"), Visibility::Writable),
        (Cow::Borrowed("ondblclick"), Visibility::Writable),
        (Cow::Borrowed("ondevicemotion"), Visibility::Writable),
        (Cow::Borrowed("ondeviceorientation"), Visibility::Writable),
        (
            Cow::Borrowed("ondeviceorientationabsolute"),
            Visibility::Writable,
        ),
        (Cow::Borrowed("ondrag"), Visibility::Writable),
        (Cow::Borrowed("ondragend"), Visibility::Writable),
        (Cow::Borrowed("ondragenter"), Visibility::Writable),
        (Cow::Borrowed("ondragleave"), Visibility::Writable),
        (Cow::Borrowed("ondragover"), Visibility::Writable),
        (Cow::Borrowed("ondragstart"), Visibility::Writable),
        (Cow::Borrowed("ondrop"), Visibility::Writable),
        (Cow::Borrowed("ondurationchange"), Visibility::Writable),
        (Cow::Borrowed("onemptied"), Visibility::Writable),
        (Cow::Borrowed("onended"), Visibility::Writable),
        (Cow::Borrowed("onerror"), Visibility::Writable),
        (Cow::Borrowed("onfocus"), Visibility::Writable),
        (Cow::Borrowed("ongotpointercapture"), Visibility::Writable),
        (Cow::Borrowed("onhashchange"), Visibility::Writable),
        (Cow::Borrowed("oninput"), Visibility::Writable),
        (Cow::Borrowed("oninvalid"), Visibility::Writable),
        (Cow::Borrowed("onkeydown"), Visibility::Writable),
        (Cow::Borrowed("onkeypress"), Visibility::Writable),
        (Cow::Borrowed("onkeyup"), Visibility::Writable),
        (Cow::Borrowed("onlanguagechange"), Visibility::Writable),
        (Cow::Borrowed("onload"), Visibility::Writable),
        (Cow::Borrowed("onloadeddata"), Visibility::Writable),
        (Cow::Borrowed("onloadedmetadata"), Visibility::Writable),
        (Cow::Borrowed("onloadstart"), Visibility::Writable),
        (Cow::Borrowed("onlostpointercapture"), Visibility::Writable),
        (Cow::Borrowed("onmessage"), Visibility::Writable),
        (Cow::Borrowed("onmessageerror"), Visibility::Writable),
        (Cow::Borrowed("onmousedown"), Visibility::Writable),
        (Cow::Borrowed("onmouseenter"), Visibility::Writable),
        (Cow::Borrowed("onmouseleave"), Visibility::Writable),
        (Cow::Borrowed("onmousemove"), Visibility::Writable),
        (Cow::Borrowed("onmouseout"), Visibility::Writable),
        (Cow::Borrowed("onmouseover"), Visibility::Writable),
        (Cow::Borrowed("onmouseup"), Visibility::Writable),
        (Cow::Borrowed("onmousewheel"), Visibility::Writable),
        (Cow::Borrowed("onoffline"), Visibility::Writable),
        (Cow::Borrowed("ononline"), Visibility::Writable),
        (Cow::Borrowed("onpagehide"), Visibility::Writable),
        (Cow::Borrowed("onpageshow"), Visibility::Writable),
        (Cow::Borrowed("onpause"), Visibility::Writable),
        (Cow::Borrowed("onplay"), Visibility::Writable),
        (Cow::Borrowed("onplaying"), Visibility::Writable),
        (Cow::Borrowed("onpointercancel"), Visibility::Writable),
        (Cow::Borrowed("onpointerdown"), Visibility::Writable),
        (Cow::Borrowed("onpointerenter"), Visibility::Writable),
        (Cow::Borrowed("onpointerleave"), Visibility::Writable),
        (Cow::Borrowed("onpointermove"), Visibility::Writable),
        (Cow::Borrowed("onpointerout"), Visibility::Writable),
        (Cow::Borrowed("onpointerover"), Visibility::Writable),
        (Cow::Borrowed("onpointerup"), Visibility::Writable),
        (Cow::Borrowed("onpopstate"), Visibility::Writable),
        (Cow::Borrowed("onprogress"), Visibility::Writable),
        (Cow::Borrowed("onratechange"), Visibility::Writable),
        (Cow::Borrowed("onrejectionhandled"), Visibility::Writable),
        (Cow::Borrowed("onreset"), Visibility::Writable),
        (Cow::Borrowed("onresize"), Visibility::Writable),
        (Cow::Borrowed("onscroll"), Visibility::Writable),
        (Cow::Borrowed("onsearch"), Visibility::Writable),
        (Cow::Borrowed("onseeked"), Visibility::Writable),
        (Cow::Borrowed("onseeking"), Visibility::Writable),
        (Cow::Borrowed("onselect"), Visibility::Writable),
        (Cow::Borrowed("onstalled"), Visibility::Writable),
        (Cow::Borrowed("onstorage"), Visibility::Writable),
        (Cow::Borrowed("onsubmit"), Visibility::Writable),
        (Cow::Borrowed("onsuspend"), Visibility::Writable),
        (Cow::Borrowed("ontimeupdate"), Visibility::Writable),
        (Cow::Borrowed("ontoggle"), Visibility::Writable),
        (Cow::Borrowed("ontransitionend"), Visibility::Writable),
        (Cow::Borrowed("onunhandledrejection"), Visibility::Writable),
        (Cow::Borrowed("onunload"), Visibility::Writable),
        (Cow::Borrowed("onvolumechange"), Visibility::Writable),
        (Cow::Borrowed("onwaiting"), Visibility::Writable),
        (Cow::Borrowed("onwheel"), Visibility::Writable),
        (Cow::Borrowed("open"), Visibility::Readonly),
        (Cow::Borrowed("openDatabase"), Visibility::Readonly),
        (Cow::Borrowed("opener"), Visibility::Readonly),
        (Cow::Borrowed("Option"), Visibility::Readonly),
        (Cow::Borrowed("origin"), Visibility::Readonly),
        (Cow::Borrowed("OscillatorNode"), Visibility::Readonly),
        (Cow::Borrowed("outerHeight"), Visibility::Readonly),
        (Cow::Borrowed("outerWidth"), Visibility::Readonly),
        (Cow::Borrowed("OverconstrainedError"), Visibility::Readonly),
        (Cow::Borrowed("PageTransitionEvent"), Visibility::Readonly),
        (Cow::Borrowed("pageXOffset"), Visibility::Readonly),
        (Cow::Borrowed("pageYOffset"), Visibility::Readonly),
        (Cow::Borrowed("PannerNode"), Visibility::Readonly),
        (Cow::Borrowed("parent"), Visibility::Readonly),
        (Cow::Borrowed("Path2D"), Visibility::Readonly),
        (Cow::Borrowed("PaymentAddress"), Visibility::Readonly),
        (Cow::Borrowed("PaymentRequest"), Visibility::Readonly),
        (
            Cow::Borrowed("PaymentRequestUpdateEvent"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("PaymentResponse"), Visibility::Readonly),
        (Cow::Borrowed("performance"), Visibility::Readonly),
        (Cow::Borrowed("Performance"), Visibility::Readonly),
        (Cow::Borrowed("PerformanceEntry"), Visibility::Readonly),
        (
            Cow::Borrowed("PerformanceLongTaskTiming"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("PerformanceMark"), Visibility::Readonly),
        (Cow::Borrowed("PerformanceMeasure"), Visibility::Readonly),
        (Cow::Borrowed("PerformanceNavigation"), Visibility::Readonly),
        (
            Cow::Borrowed("PerformanceNavigationTiming"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("PerformanceObserver"), Visibility::Readonly),
        (
            Cow::Borrowed("PerformanceObserverEntryList"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("PerformancePaintTiming"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("PerformanceResourceTiming"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("PerformanceTiming"), Visibility::Readonly),
        (Cow::Borrowed("PeriodicWave"), Visibility::Readonly),
        (Cow::Borrowed("Permissions"), Visibility::Readonly),
        (Cow::Borrowed("PermissionStatus"), Visibility::Readonly),
        (Cow::Borrowed("personalbar"), Visibility::Readonly),
        (Cow::Borrowed("PhotoCapabilities"), Visibility::Readonly),
        (Cow::Borrowed("Plugin"), Visibility::Readonly),
        (Cow::Borrowed("PluginArray"), Visibility::Readonly),
        (Cow::Borrowed("PointerEvent"), Visibility::Readonly),
        (Cow::Borrowed("PopStateEvent"), Visibility::Readonly),
        (Cow::Borrowed("postMessage"), Visibility::Readonly),
        (Cow::Borrowed("Presentation"), Visibility::Readonly),
        (
            Cow::Borrowed("PresentationAvailability"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("PresentationConnection"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("PresentationConnectionAvailableEvent"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("PresentationConnectionCloseEvent"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("PresentationConnectionList"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("PresentationReceiver"), Visibility::Readonly),
        (Cow::Borrowed("PresentationRequest"), Visibility::Readonly),
        (Cow::Borrowed("print"), Visibility::Readonly),
        (Cow::Borrowed("ProcessingInstruction"), Visibility::Readonly),
        (Cow::Borrowed("ProgressEvent"), Visibility::Readonly),
        (Cow::Borrowed("PromiseRejectionEvent"), Visibility::Readonly),
        (Cow::Borrowed("prompt"), Visibility::Readonly),
        (Cow::Borrowed("PushManager"), Visibility::Readonly),
        (Cow::Borrowed("PushSubscription"), Visibility::Readonly),
        (
            Cow::Borrowed("PushSubscriptionOptions"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("queueMicrotask"), Visibility::Readonly),
        (Cow::Borrowed("RadioNodeList"), Visibility::Readonly),
        (Cow::Borrowed("Range"), Visibility::Readonly),
        (
            Cow::Borrowed("ReadableByteStreamController"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("ReadableStream"), Visibility::Readonly),
        (
            Cow::Borrowed("ReadableStreamBYOBReader"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("ReadableStreamBYOBRequest"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("ReadableStreamDefaultController"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("ReadableStreamDefaultReader"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("registerProcessor"), Visibility::Readonly),
        (Cow::Borrowed("RemotePlayback"), Visibility::Readonly),
        (Cow::Borrowed("removeEventListener"), Visibility::Readonly),
        (Cow::Borrowed("reportError"), Visibility::Readonly),
        (Cow::Borrowed("Request"), Visibility::Readonly),
        (Cow::Borrowed("requestAnimationFrame"), Visibility::Readonly),
        (Cow::Borrowed("requestIdleCallback"), Visibility::Readonly),
        (Cow::Borrowed("resizeBy"), Visibility::Readonly),
        (Cow::Borrowed("ResizeObserver"), Visibility::Readonly),
        (Cow::Borrowed("ResizeObserverEntry"), Visibility::Readonly),
        (Cow::Borrowed("resizeTo"), Visibility::Readonly),
        (Cow::Borrowed("Response"), Visibility::Readonly),
        (Cow::Borrowed("RTCCertificate"), Visibility::Readonly),
        (Cow::Borrowed("RTCDataChannel"), Visibility::Readonly),
        (Cow::Borrowed("RTCDataChannelEvent"), Visibility::Readonly),
        (Cow::Borrowed("RTCDtlsTransport"), Visibility::Readonly),
        (Cow::Borrowed("RTCIceCandidate"), Visibility::Readonly),
        (Cow::Borrowed("RTCIceGatherer"), Visibility::Readonly),
        (Cow::Borrowed("RTCIceTransport"), Visibility::Readonly),
        (Cow::Borrowed("RTCPeerConnection"), Visibility::Readonly),
        (
            Cow::Borrowed("RTCPeerConnectionIceEvent"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("RTCRtpContributingSource"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("RTCRtpReceiver"), Visibility::Readonly),
        (Cow::Borrowed("RTCRtpSender"), Visibility::Readonly),
        (Cow::Borrowed("RTCSctpTransport"), Visibility::Readonly),
        (Cow::Borrowed("RTCSessionDescription"), Visibility::Readonly),
        (Cow::Borrowed("RTCStatsReport"), Visibility::Readonly),
        (Cow::Borrowed("RTCTrackEvent"), Visibility::Readonly),
        (Cow::Borrowed("screen"), Visibility::Readonly),
        (Cow::Borrowed("Screen"), Visibility::Readonly),
        (Cow::Borrowed("screenLeft"), Visibility::Readonly),
        (Cow::Borrowed("ScreenOrientation"), Visibility::Readonly),
        (Cow::Borrowed("screenTop"), Visibility::Readonly),
        (Cow::Borrowed("screenX"), Visibility::Readonly),
        (Cow::Borrowed("screenY"), Visibility::Readonly),
        (Cow::Borrowed("ScriptProcessorNode"), Visibility::Readonly),
        (Cow::Borrowed("scroll"), Visibility::Readonly),
        (Cow::Borrowed("scrollbars"), Visibility::Readonly),
        (Cow::Borrowed("scrollBy"), Visibility::Readonly),
        (Cow::Borrowed("scrollTo"), Visibility::Readonly),
        (Cow::Borrowed("scrollX"), Visibility::Readonly),
        (Cow::Borrowed("scrollY"), Visibility::Readonly),
        (
            Cow::Borrowed("SecurityPolicyViolationEvent"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("Selection"), Visibility::Readonly),
        (Cow::Borrowed("self"), Visibility::Readonly),
        (Cow::Borrowed("ServiceWorker"), Visibility::Readonly),
        (
            Cow::Borrowed("ServiceWorkerContainer"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("ServiceWorkerRegistration"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("sessionStorage"), Visibility::Readonly),
        (Cow::Borrowed("setInterval"), Visibility::Readonly),
        (Cow::Borrowed("setTimeout"), Visibility::Readonly),
        (Cow::Borrowed("ShadowRoot"), Visibility::Readonly),
        (Cow::Borrowed("SharedWorker"), Visibility::Readonly),
        (Cow::Borrowed("SourceBuffer"), Visibility::Readonly),
        (Cow::Borrowed("SourceBufferList"), Visibility::Readonly),
        (Cow::Borrowed("speechSynthesis"), Visibility::Readonly),
        (Cow::Borrowed("SpeechSynthesisEvent"), Visibility::Readonly),
        (
            Cow::Borrowed("SpeechSynthesisUtterance"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("StaticRange"), Visibility::Readonly),
        (Cow::Borrowed("status"), Visibility::Readonly),
        (Cow::Borrowed("statusbar"), Visibility::Readonly),
        (Cow::Borrowed("StereoPannerNode"), Visibility::Readonly),
        (Cow::Borrowed("stop"), Visibility::Readonly),
        (Cow::Borrowed("Storage"), Visibility::Readonly),
        (Cow::Borrowed("StorageEvent"), Visibility::Readonly),
        (Cow::Borrowed("StorageManager"), Visibility::Readonly),
        (Cow::Borrowed("structuredClone"), Visibility::Readonly),
        (Cow::Borrowed("styleMedia"), Visibility::Readonly),
        (Cow::Borrowed("StyleSheet"), Visibility::Readonly),
        (Cow::Borrowed("StyleSheetList"), Visibility::Readonly),
        (Cow::Borrowed("SubmitEvent"), Visibility::Readonly),
        (Cow::Borrowed("SubtleCrypto"), Visibility::Readonly),
        (Cow::Borrowed("SVGAElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGAngle"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedAngle"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedBoolean"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGAnimatedEnumeration"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGAnimatedInteger"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedLength"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedLengthList"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedNumber"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedNumberList"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGAnimatedPreserveAspectRatio"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGAnimatedRect"), Visibility::Readonly),
        (Cow::Borrowed("SVGAnimatedString"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGAnimatedTransformList"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGAnimateElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGAnimateMotionElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGAnimateTransformElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGAnimationElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGCircleElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGClipPathElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGComponentTransferFunctionElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGDefsElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGDescElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGDiscardElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGEllipseElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEBlendElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGFEColorMatrixElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGFEComponentTransferElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGFECompositeElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGFEConvolveMatrixElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGFEDiffuseLightingElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGFEDisplacementMapElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGFEDistantLightElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGFEDropShadowElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGFEFloodElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEFuncAElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEFuncBElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEFuncGElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEFuncRElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGFEGaussianBlurElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGFEImageElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEMergeElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFEMergeNodeElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGFEMorphologyElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGFEOffsetElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGFEPointLightElement"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGFESpecularLightingElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGFESpotLightElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGFETileElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGFETurbulenceElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGFilterElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGForeignObjectElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGGElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGGeometryElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGGradientElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGGraphicsElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGImageElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGLength"), Visibility::Readonly),
        (Cow::Borrowed("SVGLengthList"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGLinearGradientElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGLineElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGMarkerElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGMaskElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGMatrix"), Visibility::Readonly),
        (Cow::Borrowed("SVGMetadataElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGMPathElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGNumber"), Visibility::Readonly),
        (Cow::Borrowed("SVGNumberList"), Visibility::Readonly),
        (Cow::Borrowed("SVGPathElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGPatternElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGPoint"), Visibility::Readonly),
        (Cow::Borrowed("SVGPointList"), Visibility::Readonly),
        (Cow::Borrowed("SVGPolygonElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGPolylineElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGPreserveAspectRatio"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("SVGRadialGradientElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGRect"), Visibility::Readonly),
        (Cow::Borrowed("SVGRectElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGScriptElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGSetElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGStopElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGStringList"), Visibility::Readonly),
        (Cow::Borrowed("SVGStyleElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGSVGElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGSwitchElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGSymbolElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGTextContentElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGTextElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGTextPathElement"), Visibility::Readonly),
        (
            Cow::Borrowed("SVGTextPositioningElement"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("SVGTitleElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGTransform"), Visibility::Readonly),
        (Cow::Borrowed("SVGTransformList"), Visibility::Readonly),
        (Cow::Borrowed("SVGTSpanElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGUnitTypes"), Visibility::Readonly),
        (Cow::Borrowed("SVGUseElement"), Visibility::Readonly),
        (Cow::Borrowed("SVGViewElement"), Visibility::Readonly),
        (Cow::Borrowed("TaskAttributionTiming"), Visibility::Readonly),
        (Cow::Borrowed("Text"), Visibility::Readonly),
        (Cow::Borrowed("TextDecoder"), Visibility::Readonly),
        (Cow::Borrowed("TextDecoderStream"), Visibility::Readonly),
        (Cow::Borrowed("TextEncoder"), Visibility::Readonly),
        (Cow::Borrowed("TextEncoderStream"), Visibility::Readonly),
        (Cow::Borrowed("TextEvent"), Visibility::Readonly),
        (Cow::Borrowed("TextMetrics"), Visibility::Readonly),
        (Cow::Borrowed("TextTrack"), Visibility::Readonly),
        (Cow::Borrowed("TextTrackCue"), Visibility::Readonly),
        (Cow::Borrowed("TextTrackCueList"), Visibility::Readonly),
        (Cow::Borrowed("TextTrackList"), Visibility::Readonly),
        (Cow::Borrowed("TimeRanges"), Visibility::Readonly),
        (Cow::Borrowed("ToggleEvent"), Visibility::Readonly),
        (Cow::Borrowed("toolbar"), Visibility::Readonly),
        (Cow::Borrowed("top"), Visibility::Readonly),
        (Cow::Borrowed("Touch"), Visibility::Readonly),
        (Cow::Borrowed("TouchEvent"), Visibility::Readonly),
        (Cow::Borrowed("TouchList"), Visibility::Readonly),
        (Cow::Borrowed("TrackEvent"), Visibility::Readonly),
        (Cow::Borrowed("TransformStream"), Visibility::Readonly),
        (
            Cow::Borrowed("TransformStreamDefaultController"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("TransitionEvent"), Visibility::Readonly),
        (Cow::Borrowed("TreeWalker"), Visibility::Readonly),
        (Cow::Borrowed("UIEvent"), Visibility::Readonly),
        (Cow::Borrowed("URL"), Visibility::Readonly),
        (Cow::Borrowed("URLSearchParams"), Visibility::Readonly),
        (Cow::Borrowed("ValidityState"), Visibility::Readonly),
        (Cow::Borrowed("visualViewport"), Visibility::Readonly),
        (Cow::Borrowed("VisualViewport"), Visibility::Readonly),
        (Cow::Borrowed("VTTCue"), Visibility::Readonly),
        (Cow::Borrowed("WaveShaperNode"), Visibility::Readonly),
        (Cow::Borrowed("WebAssembly"), Visibility::Readonly),
        (
            Cow::Borrowed("WebGL2RenderingContext"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("WebGLActiveInfo"), Visibility::Readonly),
        (Cow::Borrowed("WebGLBuffer"), Visibility::Readonly),
        (Cow::Borrowed("WebGLContextEvent"), Visibility::Readonly),
        (Cow::Borrowed("WebGLFramebuffer"), Visibility::Readonly),
        (Cow::Borrowed("WebGLProgram"), Visibility::Readonly),
        (Cow::Borrowed("WebGLQuery"), Visibility::Readonly),
        (Cow::Borrowed("WebGLRenderbuffer"), Visibility::Readonly),
        (Cow::Borrowed("WebGLRenderingContext"), Visibility::Readonly),
        (Cow::Borrowed("WebGLSampler"), Visibility::Readonly),
        (Cow::Borrowed("WebGLShader"), Visibility::Readonly),
        (
            Cow::Borrowed("WebGLShaderPrecisionFormat"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("WebGLSync"), Visibility::Readonly),
        (Cow::Borrowed("WebGLTexture"), Visibility::Readonly),
        (
            Cow::Borrowed("WebGLTransformFeedback"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("WebGLUniformLocation"), Visibility::Readonly),
        (
            Cow::Borrowed("WebGLVertexArrayObject"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("WebSocket"), Visibility::Readonly),
        (Cow::Borrowed("WheelEvent"), Visibility::Readonly),
        (Cow::Borrowed("window"), Visibility::Readonly),
        (Cow::Borrowed("Window"), Visibility::Readonly),
        (Cow::Borrowed("Worker"), Visibility::Readonly),
        (Cow::Borrowed("WritableStream"), Visibility::Readonly),
        (
            Cow::Borrowed("WritableStreamDefaultController"),
            Visibility::Readonly,
        ),
        (
            Cow::Borrowed("WritableStreamDefaultWriter"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("XMLDocument"), Visibility::Readonly),
        (Cow::Borrowed("XMLHttpRequest"), Visibility::Readonly),
        (
            Cow::Borrowed("XMLHttpRequestEventTarget"),
            Visibility::Readonly,
        ),
        (Cow::Borrowed("XMLHttpRequestUpload"), Visibility::Readonly),
        (Cow::Borrowed("XMLSerializer"), Visibility::Readonly),
        (Cow::Borrowed("XPathEvaluator"), Visibility::Readonly),
        (Cow::Borrowed("XPathExpression"), Visibility::Readonly),
        (Cow::Borrowed("XPathResult"), Visibility::Readonly),
        (Cow::Borrowed("XSLTProcessor"), Visibility::Readonly),
    ]
    .into()
});

#[cfg(test)]
mod tests {
    use speculoos::prelude::*;

    use super::*;

    #[test]
    fn test_deserialize_visibility() {
        [
            (r#""off""#, Visibility::Off),
            (r#"true"#, Visibility::Writable),
            (r#""true""#, Visibility::Writable),
            (r#"false"#, Visibility::Readonly),
            (r#""false""#, Visibility::Readonly),
            (r#"null"#, Visibility::Readonly),
            (r#""writeable""#, Visibility::Writable),
            (r#""writable""#, Visibility::Writable),
            (r#""readable""#, Visibility::Readonly),
            (r#""readonly""#, Visibility::Readonly),
            (r#""writable""#, Visibility::Writable),
        ]
        .into_iter()
        .for_each(|(input, output)| {
            let deserialized: Visibility = serde_json::from_str(input).unwrap();
            assert_that!(&deserialized).is_equal_to(output);
        });

        let deserialized: Result<Visibility, _> = serde_json::from_str("something else");
        assert_that!(&deserialized).is_err();
    }
}
